name: Actualizacion de Precios
on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v3
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Instalar librerias
        run: |
          pip install requests beautifulsoup4
          
      - name: Ejecutar Scraping
        run: python actualizador.py
        
      - name: Guardar cambios en GitHub
        run: |
          git config --global user.name 'Bot Precios'
          git config --global user.email 'bot@precios.com'
          git add base_de_datos_precio.json
          git commit -m "Precios actualizados $(date)" || echo "Sin cambios detectados"
          git push
